---
Environment: Development

Secret: test
InitialAdminPassword: password

UseMailServer: true
MailServer:
  From: Holvit Develop <no-reply@holvit.develop>
  Host: localhost
  Port: 1025
  StartTls:      false
  AllowInsecure: true

Database:
#  Database: holvit
  Username: user
  Password: password
#  Host: localhost
  Port: 5783
