version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5783:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: holvit