###
# @no-redirect
GET localhost:8080/oidc/admin/authorize?state=test&scope={{scope}}&response_type=code&client_id={{client_id}}&
    redirect_uri={{redirect_uri}}

> {%
    const code = response.headers.valueOf('Location').match(/code=(.*?)&/)[1];
    client.global.set('code', code);
%}



### get tokens using authorization code
< {%
 client.global.set('code', 'QoZqtnb%2B2gKkkBXhhuSit3HYWDpelY3%2BKEp%2BwlKfcS0%3D')
%}
POST localhost:8080/oidc/admin/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}} {{client_secret}}

grant_type = authorization_code &
redirect_uri = {{redirect_uri}} &
code = {{code}}

> {%
    const refreshToken = response.body.refresh_token;
    const accessToken = response.body.access_token;
    const idToken = response.body.id_token;
    client.global.set('refreshToken', refreshToken)
    client.global.set('access_token', accessToken)
    client.global.set('id_token', idToken)
%}


### get tokens using refresh token
POST localhost:8080/oidc/admin/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_id}} {{client_secret}}

grant_type = refresh_token &
scope = {{scope}} &
redirect_uri = {{redirect_uri}} &
refresh_token = {{refreshToken}}

> {%
    if (response.status === 200) {
        const refreshToken = response.body.refresh_token;
        client.global.set('refreshToken', refreshToken)
    }
%}


### get userinfo
GET localhost:8080/oidc/admin/userinfo
Authorization: Bearer {{accessToken}}

